# Linear Regression

## Import libraries and data

In [325]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns
from seaborn import regplot

import statsmodels.formula.api as smf
import statsmodels.api as sm
import statsmodels.stats.multicomp as multi

import scipy
from scipy import stats
from scipy.stats import pearsonr

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import QuantileTransformer
from sklearn.preprocessing import PowerTransformer

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

import researchpy as rp

import plotly.express as px

import statistics

In [326]:
from gapminder import gapminder

## Workflow

In [ ]:
# Create variables (dummy variables)

# X = df.drop(columns=['country', 'continent', 'gdp_per_cap'])
# Y = df.gdp_per_cap

# df_dummy = df.drop(columns=['country'])
# df_dummy = pd.get_dummies(df_dummy)
# X_dummy = df_dummy.drop(columns=['gdp_per_cap'])

In [ ]:
# Scale data (scaler, transform)

# scaler_standard = StandardScaler()
# scaler_standard.fit(X)
# X = scaler_standard.transform(X)

In [ ]:
# Split data set

# x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [412]:
# Initiate model

# model = LinearRegression()

In [413]:
# Fit model

# results = model.fit(x_train, y_train)

In [ ]:
# Predict values

# y_predict = model.predict(x_test)

In [ ]:
# Calculate R2
# score_scaler = r2_score(y_test,y_predict)
# score_scaler

## Import data

In [327]:
df = gapminder

In [328]:
df = df.rename(columns={'lifeExp':'life_exp', 'pop':'population', 'gdpPercap':'gdp_per_cap'})

In [329]:
df.head()

country continent  year  life_exp  population  gdp_per_cap
0  Afghanistan      Asia  1952    28.801     8425333   779.445314
1  Afghanistan      Asia  1957    30.332     9240934   820.853030
2  Afghanistan      Asia  1962    31.997    10267083   853.100710
3  Afghanistan      Asia  1967    34.020    11537966   836.197138
4  Afghanistan      Asia  1972    36.088    13079460   739.981106

In [330]:
df.corr()

year  life_exp  population  gdp_per_cap
year         1.000000  0.435611    0.082308     0.227318
life_exp     0.435611  1.000000    0.064955     0.583706
population   0.082308  0.064955    1.000000    -0.025600
gdp_per_cap  0.227318  0.583706   -0.025600     1.000000

## Implement linear regression model

### Create variables

In [331]:
X = df.drop(columns=['country', 'continent', 'gdp_per_cap'])

In [332]:
Y = df.gdp_per_cap

### statsmodels

In [333]:
X = sm.add_constant(X)

In [334]:
model_constant = sm.OLS(Y,X)

In [335]:
results_constant = model_constant.fit()

In [336]:
results_constant.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            gdp_per_cap   R-squared:                       0.345
Model:                            OLS   Adj. R-squared:                  0.344
Method:                 Least Squares   F-statistic:                     299.1
Date:                Thu, 21 Jul 2022   Prob (F-statistic):          6.91e-156
Time:                        10:46:31   Log-Likelihood:                -17726.
No. Observations:                1704   AIC:                         3.546e+04
Df Residuals:                    1700   BIC:                         3.548e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.304e+04   2.43e+04      0.537      0.591   -3.46e+04    6.06e+04
year         -16.6235     12.469     -1.333      0.183     -41.079       7.832
life_exp     458.2072     16.644     27.529      0.000     425.562     490.853
population -5.776e-06   1.83e-06     -3.158      0.002   -9.36e-06   -2.19e-06
==============================================================================
Omnibus:                     1946.747   Durbin-Watson:                   0.330
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           264041.825
Skew:                           5.623   Prob(JB):                         0.00
Kurtosis:                      62.937   Cond. No.                     1.38e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.38e+10. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### sklearn

In [337]:
model = LinearRegression()

In [338]:
results = model.fit(X, Y)

In [339]:
results.coef_

array([ 0.00000000e+00, -1.66235076e+01,  4.58207190e+02, -5.77607025e-06])

In [340]:
results.intercept_

13040.923403524965

In [341]:
results.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

### Dummy variables for continent

In [342]:
df_dummy = df.drop(columns=['country'])

In [343]:
df_dummy = pd.get_dummies(df_dummy)

In [344]:
X_dummy = df_dummy.drop(columns=['gdp_per_cap'])

In [345]:
Y_dummy = df_dummy.gdp_per_cap

In [346]:
X_dummy = sm.add_constant(X_dummy)

In [347]:
model_dummy_continent = sm.OLS(Y_dummy,X_dummy)

In [348]:
results_dummy_continent = model_dummy_continent.fit()

In [349]:
results_dummy_continent.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            gdp_per_cap   R-squared:                       0.369
Model:                            OLS   Adj. R-squared:                  0.366
Method:                 Least Squares   F-statistic:                     141.4
Date:                Thu, 21 Jul 2022   Prob (F-statistic):          2.66e-164
Time:                        10:46:32   Log-Likelihood:                -17696.
No. Observations:                1704   AIC:                         3.541e+04
Df Residuals:                    1696   BIC:                         3.545e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const              -2.292e+04   2.22e+04     -1.034      0.301   -6.64e+04    2.06e+04
year                   6.5271     13.939      0.468      0.640     -20.812      33.866
life_exp             388.1655     26.037     14.908      0.000     337.097     439.234
population         -6.416e-06   1.86e-06     -3.454      0.001   -1.01e-05   -2.77e-06
continent_Africa   -6707.6449   4688.123     -1.431      0.153   -1.59e+04    2487.469
continent_Americas -7802.1451   4450.063     -1.753      0.080   -1.65e+04     926.046
continent_Asia     -4915.8884   4509.084     -1.090      0.276   -1.38e+04    3928.066
continent_Europe   -3328.0795   4345.070     -0.766      0.444   -1.19e+04    5194.183
continent_Oceania   -169.5052   4494.343     -0.038      0.970   -8984.547    8645.536
==============================================================================
Omnibus:                     1996.307   Durbin-Watson:                   0.332
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           299082.688
Skew:                           5.848   Prob(JB):                         0.00
Kurtosis:                      66.841   Cond. No.                     5.55e+23
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.72e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

## Machine learning

In [350]:
# https://towardsdatascience.com/all-about-feature-scaling-bcc0ad75cb35

In [351]:
x = X
y = Y

In [353]:
x.corr()
# < 0.7 / no multicollinearity (VIF)

const      year  life_exp  population
const         NaN       NaN       NaN         NaN
year          NaN  1.000000  0.435611    0.082308
life_exp      NaN  0.435611  1.000000    0.064955
population    NaN  0.082308  0.064955    1.000000

In [354]:
# Split data set (years, random)

In [355]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [356]:
# OLS

In [357]:
model_OLS = sm.OLS(y_train, x_train)

In [358]:
results_OLS = model_OLS.fit()

In [359]:
# Predict values
y_predict = model.predict(x_test)

In [360]:
# R2 score
score = r2_score(y_test,y_predict)
score

0.4863448445972305

In [361]:
# Mean squared error
mean_squared_error(y_test,y_predict)
np.sqrt(mean_squared_error(y_test,y_predict))

5944.000649407297

In [362]:
# Sklearn

In [363]:
model = LinearRegression()

In [364]:
results = model.fit(x_train, y_train)

In [367]:
# Predict values

In [368]:
y_predict = model.predict(x_test)

In [369]:
# R2 score

In [370]:
score = r2_score(y_test,y_predict)
score

0.48300210491065754

In [371]:
# Mean squared error

In [411]:
mean_squared_error(y_test,y_predict)
np.sqrt(mean_squared_error(y_test,y_predict))

5963.310321851847

### Scaler

In [386]:
# Normalization is used when we want to bound our values between two numbers, typically, between [0,1] or [-1,1]. 
# While Standardization transforms the data to have zero mean and a variance of 1, they make our data unitless. 

In [387]:
# Scale data
scaler_standard = StandardScaler()

In [388]:
scaler_standard.fit(X)

StandardScaler()

In [389]:
X_train_scaled = scaler_standard.transform(X)

In [390]:
x_train, x_test, y_train, y_test = train_test_split(X_train_scaled, Y, test_size = 0.2, random_state = 42)

In [391]:
model_scaler = LinearRegression()

In [392]:
results_scaler = model_scaler.fit(x_train, y_train)

In [393]:
y_predict_scaler = model_scaler.predict(x_test)

In [394]:
score_scaler = r2_score(y_test,y_predict_scaler)
score_scaler

0.48300210490971884

### Test heteroscedacity 

In [406]:
y = y_predict - y_test

In [379]:
y = y.tolist()

In [380]:
y_mean = sum(y)/len(y)
y_std = statistics.stdev(y)

In [381]:
y_predict_mean = sum(y_predict)/len(y_predict)
y_predict_std = statistics.stdev(y_predict)

In [382]:
y_predict = y_predict.tolist() 

In [383]:
residuals = pd.DataFrame(y, y_predict, columns=['residuals']).reset_index().rename(columns={'index':'predict'})

In [384]:
residuals['predict_stand'] = (residuals.predict-y_predict_mean)/y_predict_std
residuals['residuals_stand'] = (residuals.residuals-y_mean)/y_predict_std
residuals

predict    residuals  predict_stand  residuals_stand
0     1187.221230   799.221230      -1.142090         0.057927
1    12301.334488  6702.256616       0.879517         1.131662
2    12397.542791  5747.347218       0.897016         0.957969
3     5052.257711  2895.301642      -0.439058         0.439195
4    10654.877006  7672.775148       0.580033         1.308195
..            ...          ...            ...              ...
336   4636.198082  3444.990401      -0.514737         0.539180
337   1650.373856   956.261417      -1.057845         0.086492
338   4871.142034  2268.431865      -0.472002         0.325170
339   6154.899248  1275.391726      -0.238492         0.144540
340  11112.104033  6547.301623       0.663201         1.103477

[341 rows x 4 columns]

In [374]:
# Visualize results

In [375]:
prediction = pd.DataFrame(y_predict, y_test, columns=['test']).reset_index()

In [376]:
prediction = prediction.rename(columns={'gdp_per_cap':'predict'})

In [410]:
fig = px.scatter(prediction, x='test', y='predict')
fig.show()

In [395]:
# Create loop

In [396]:
scaler_list = [StandardScaler, MinMaxScaler, MaxAbsScaler, RobustScaler, Normalizer, QuantileTransformer, PowerTransformer]

In [397]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [398]:
for i in range(0, len(scaler_list)):
    scaler = scaler_list[i]()
    scaler.fit(x_train)
    x_train_scaled = scaler.transform(x_train)
    model = LinearRegression()
    results = model.fit(x_train_scaled, y_train)
    print(scaler_list[i])
    print(results.coef_)

# interpretation of results?

<class 'sklearn.preprocessing._data.StandardScaler'>
[   0.         -401.67444365 5960.82575211 -588.54086845]
<class 'sklearn.preprocessing._data.MinMaxScaler'>
[    0.         -1268.05342722 26960.68950349 -8103.78715061]
<class 'sklearn.preprocessing._data.MaxAbsScaler'>
[     0.         -46272.42233526  37743.77728725  -8104.16403257]
<class 'sklearn.preprocessing._data.RobustScaler'>
[    0.          -691.66550576 10513.72763085  -100.99877367]
<class 'sklearn.preprocessing._data.Normalizer'>
[ 1.31625545e+11 -7.12367036e+07  1.79974152e+08  4.14444642e+07]
<class 'sklearn.preprocessing._data.QuantileTransformer'>
[    0.         -1568.33757913 22112.1513066  -3314.48737566]
<class 'sklearn.preprocessing._data.PowerTransformer'>
[   0.         -495.75594876 6098.3257902     0.        ]


/Users/anneruhnke/opt/anaconda3/lib/python3.8/site-packages/sklearn/preprocessing/_data.py:3237: RuntimeWarning:

divide by zero encountered in log

