# Logistic Regression

## Import libraries and data

In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns
from seaborn import regplot

import statsmodels.formula.api as smf
import statsmodels.api as sm
import statsmodels.stats.multicomp as multi

import scipy
from scipy import stats
from scipy.stats import pearsonr

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

import researchpy as rp

import plotly.express as px

In [22]:
df = pd.read_csv('data.csv')

In [23]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [24]:
df = df.rename(columns={'PatientId':'patient_id', 'AppointmentID':'appointment_id', 'Gender':'gender', 
                        'ScheduledDay':'scheduled_day', 'AppointmentDay':'appointment_day', 'Age': 'age', 
                        'Neighbourhood':'neighbourhood', 'Scholarship':'scholarship', 'Hipertension':'hipertension', 
                        'Diabetes':'diabetes', 'Alcoholism':'alcoholism', 'Handcap':'handicap', 'SMS_received':'sms', 
                        'No-show':'show_up'})

In [25]:
df.head()

patient_id  appointment_id  gender              scheduled_day  \
0   29872499824296         5642903       0  2016-04-29 18:38:08+00:00   
1  558997776694438         5642503       1  2016-04-29 16:08:27+00:00   
2    4262962299951         5642549       0  2016-04-29 16:19:04+00:00   
3     867951213174         5642828       0  2016-04-29 17:29:31+00:00   
4    8841186448183         5642494       0  2016-04-29 16:07:23+00:00   

             appointment_day  age      neighbourhood  scholarship  \
0  2016-04-29 00:00:00+00:00   62    JARDIM DA PENHA            0   
1  2016-04-29 00:00:00+00:00   56    JARDIM DA PENHA            0   
2  2016-04-29 00:00:00+00:00   62      MATA DA PRAIA            0   
3  2016-04-29 00:00:00+00:00    8  PONTAL DE CAMBURI            0   
4  2016-04-29 00:00:00+00:00   56    JARDIM DA PENHA            0   

   hipertension  diabetes  alcoholism  handicap  sms  show_up  
0             1         0           0         0    0        1  
1             0         0           0         0    0        1  
2             0         0           0         0    0        1  
3             0         0           0         0    0        1  
4             1         1           0         0    0        1

In [ ]:
# dummy variables necessary?
# neighbourhood?
# visualize data?
# improve prediction
# split data
# include dates (different formats)
# repeating patient_id - differences?
# delete appointment id
# format age to bins

In [40]:
df.neighbourhood.value_counts()

JARDIM CAMBURI                 7717
MARIA ORTIZ                    5804
RESISTÊNCIA                    4431
JARDIM DA PENHA                3877
ITARARÉ                        3514
                               ... 
ILHA DO BOI                      35
ILHA DO FRADE                    10
AEROPORTO                         8
ILHAS OCEÂNICAS DE TRINDADE       2
PARQUE INDUSTRIAL                 1
Name: neighbourhood, Length: 81, dtype: int64

## Implement logistic regression model

In [26]:
Y = df.show_up

In [27]:
X = df.drop(columns=['patient_id', 'appointment_id', 'scheduled_day', 'appointment_day', 'neighbourhood', 'show_up'])

In [28]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [29]:
results = model.fit(X,Y)

In [30]:
model.classes_

array([0, 1])

In [31]:
model.intercept_

array([1.38337123])

In [32]:
model.coef_

array([[ 0.01791095,  0.00660273, -0.18430819,  0.06641824, -0.0851067 ,
        -0.13930778, -0.02505656, -0.64967114]])

In [33]:
model.score(X,Y)

0.7980799681502728

In [34]:
confusion_matrix(Y, model.predict(X))

array([[    0, 22316],
       [    0, 88203]])

In [35]:
print(classification_report(Y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00     22316
           1       0.80      1.00      0.89     88203

    accuracy                           0.80    110519
   macro avg       0.40      0.50      0.44    110519
weighted avg       0.64      0.80      0.71    110519



/Users/anneruhnke/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/anneruhnke/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/anneruhnke/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
